name: Deploy Swagger UI

on:
  push:
    branches:
      - main

# Add this permissions block
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install SBT
        run: |
          echo "Installing SBT..."
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
          sudo apt-get update
          sudo apt-get install -y sbt

      - name: Build project
        run: sbt compile

      - name: Setup Swagger UI
        run: |
          # Download and extract Swagger UI
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.15.5.zip
          unzip v4.15.5.zip
          
          # Create directory for Swagger UI
          mkdir -p swagger-ui
          
          # Copy Swagger UI files
          cp -r swagger-ui-4.15.5/dist/* swagger-ui/
          
          # Copy your OpenAPI spec file to Swagger UI directory
          cp conf/openapi.json swagger-ui/ || echo "Warning: openapi.json not found in conf directory"
          
          # Configure Swagger UI to use your API spec
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|./openapi.json|g' swagger-ui/index.html
          
          # Add configuration for API execution (modify URL as needed)
          cat > swagger-ui/swagger-initializer.js << EOF
          window.onload = function() {
            window.ui = SwaggerUIBundle({
              url: "./openapi.json",
              dom_id: '#swagger-ui',
              deepLinking: true,
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
              ],
              plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
              ],
              layout: "StandaloneLayout",
              requestInterceptor: function(request) {
                const apiUrl = 'https://sashwath-kumar.github.io/'; 
                if (request.url.startsWith('/')) {
                  request.url = apiUrl + request.url;
                }
                return request;
              }
            });
          };
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui