name: Deploy Swagger UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install SBT
        run: |
          echo "Installing SBT..."
          curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.deb
          sudo dpkg -i sbt.deb
          sudo apt-get update
          sudo apt-get install sbt

      - name: Build project
        run: sbt compile

      # Add step to generate OpenAPI spec if not already in conf directory
      - name: Generate OpenAPI spec
        run: |
          # If you need to generate the spec file, uncomment and modify this line:
          # sbt "runMain your.package.GenerateSwaggerSpec"
          
          # Create directory for Swagger UI
          mkdir -p swagger-ui

      - name: Setup Swagger UI
        run: |
          # Download and extract Swagger UI
          wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v4.15.5.zip
          unzip v4.15.5.zip
          
          # Copy Swagger UI files
          cp -r swagger-ui-4.15.5/dist/* swagger-ui/
          
          # Copy your OpenAPI spec file to Swagger UI directory
          cp conf/openapi.json swagger-ui/ || echo "Warning: openapi.json not found in conf directory"
          
          # Configure Swagger UI to use your API spec
          sed -i 's|https://petstore.swagger.io/v2/swagger.json|./openapi.json|g' swagger-ui/index.html
          
          # Add configuration for API execution (modify URL as needed)
          cat > swagger-ui/swagger-initializer.js << EOF
          window.onload = function() {
            window.ui = SwaggerUIBundle({
              url: "./openapi.json",
              dom_id: '#swagger-ui',
              deepLinking: true,
              presets: [
                SwaggerUIBundle.presets.apis,
                SwaggerUIStandalonePreset
              ],
              plugins: [
                SwaggerUIBundle.plugins.DownloadUrl
              ],
              layout: "StandaloneLayout",
              requestInterceptor: function(request) {
                // Replace with your actual API URL in production
                const apiUrl = 'https://sashwath-kumar.github.io'; 
                if (request.url.startsWith('/')) {
                  request.url = apiUrl + request.url;
                }
                return request;
              }
            });
          };
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./swagger-ui