name: Deploy Swagger UI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install SBT
      run: |
        echo "Installing SBT..."
        curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.deb
        sudo dpkg -i sbt.deb
        sudo apt-get update
        sudo apt-get install sbt

    - name: Build project
      run: sbt compile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./conf